## SYSTRADER79 PYTHON BACKTEST MANUAL
이 문서는 python을 이용해서 백테스트 환경을 구축하고 실행해보는 하는 것을 목적으로 한다. 


## 1.	환경
증권사: 대신증권
개발: anaconda, pycharm or spyder
기타 추가 예정


## 2.	대신증권 설정
CYBOS5 다운로드
http://www.daishin.co.kr/ctx_kr/sc_trading_tool/sg_online/svc_ucybos/ucybos.html

참고
https://wikidocs.net/3679


# 3. 환경설정

## 3.1 Anaconda Download
다음의 위치를 참조해서 anaconda download및 설치 http://dwfox.tistory.com/67

참고로 증권사 API사용을 위해서는 32bit python이 필요하기 때문에 32bit python을 다운로드 받는 것을 추천한다. 혹시라도 64bit anaconda를 설치하였으면, 지우고 재설치를 하던가, 다음의 link를 기준으로 32bit설정을 진행한다.

http://sharebook.kr/pages/viewpage.action?pageId=9437187

## 3.2 Anaconda 설정
anaconda설치 후에 다양한 package의 업데이트가 필요하다. 이를 위해서 pip installer update가 필요한데 다음과 같다. python -m pip install --upgrade pip. 
실행방법: 
1.	윈도우에서 cmd실행
2.	python -m pip install --upgrade pip 실행
3.	win32com 설치필요 (http://guslabview.tistory.com/345) 참조

win32com의 경우는 activex의 window library를 python에서 사용하게 끔해줄 수 있는 library로 pip install로 설치되지 않으니 주의하자.

# 4. MS SQL 설정
## 4.1 MSSQL Download및 설치
MS SQL을 사용하기 위해서는 developer버전을 다운로드 받아서 설치하면 된다. 설치는 기존의 다른 프로그램들 설치와 동일하기 때문에 아래의 link를 참고해서 download받으면 된다.
https://www.youtube.com/watch?time_continue=5&v=3VGldZTzIzM

## 4.2 MS SQL Database 시작하기
Database 이하 DB를 만들고 시작 해줄 필요가 있다.

메뉴 상단의 새쿼리 버튼을 누른 후 하기의 명령어를 실행한다.


명령어의 의미는 다음과 같다.

create database stock;    --stock이라는 이름의 데이터 베이스 생성

use stock; --stock이라는 이름의 데이터 베이스 사용 시작.

## 4.3 MS SQL Database 초기화 하기
DB를 생성 후에는 DB에 사용할 데이터 포맷을 지정해줘야한다. 

아래의 link에 접속 후에 모든 code를 copy해서 SQL Server Management studio의 새 쿼리 문에 붙여 넣는다. 기본적으로 dante님의 link와 동일하다. 한가지 더 참고할 사항은 쿼리문의 한줄 주석처리는 --로 하고, 여러줄은 /**/ 로 하면 된다.

https://gist.github.com/jcoco99/4d75507a08d965eec2423da685f2e13d

위의 과정이 다 정상적으로 수행될 경우, SQL Server Management studio의 개체탐색기를 확인할 경우 아래와 같이 stock이라는 데이터베이스 밑에 dbo.LogDay등의 데이터 포맷이 만들어진 것을 볼 수 있다.

!!이미지 업데이트 필요


# 5 데이터 다운받기
## 5.1 사용할 코드 주소
단테님의 코드를 받아서 32bit python환경에서 수행하면 된다. 아래의 링크의 파일을 다운 받아서 실행하면 된다. 조금더 간단히 얘기하면 32bit spyder를 실행 후에 아래의 코드를 오픈해서 실행하면 된다. 

http://cafe.naver.com/sysdantalk/1067

실행하기 전에 Cybos Plus가 실행되어 있어야 한다. 아래의 코드를 보면 id나 비밀번호를 입력하는 부분이 없는데, Cybos Plus가 open되었을 경우에만 대신증권에 access해서 데이터를 가져올 수 있는 구조로 되어 있다. 아래의 코드 실행 전에는 꼭 Cybos Plus에 로그인 해놓자.

실행하기 전에 MS SQL Server Management studio역시 실행되어 있어야 한다. 아래의 코드는 대신증권 데이터를 바로 MS DB에 저장하기 때문에 DB가 실행이 안되있을 경우, DB가 없다는 종류의 에러메세지가 발생한다.

수행파일은 CT_get_min.py이고 수정해야될 파일은 fn_getStock_min.py이다. 2개의 파일이 디렉토리에 따라서 일봉과 분봉을 저장하는 구조로 되어 있다.
mssql_daily_creator밑의 CT_get_min.py를 실행할 경우에는 일봉을 다운로드 받는다.
mssql_minute_creator밑의 CT_get_min.py를 실행할 경우에는 분봉을 다운로드 받는다.


코드 자체에서 4.3에서 생성한 DB포맷대로 바로 저장하기 때문에 큰 문제가 없지만, fn_getStock_min.py에서 다음의 사항은 변경해줘야한다.

!!이미지 업데이트 필요.

자신의 컴퓨터에 설정한 컴퓨터 혹은 DB주소가 있을 텐데 그 부분을 copy해서 위의 fn_getStock_min.py에 넣는다.

# 6 Williams R BACKTEST
## 6.1 DB update하기
Williams R은 range를 나타내는 지표로 다음 부분을 보면 자세한 내용을 알 수 있다.
https://www.investopedia.com/terms/w/williamsr.asp

Williams R을 테스트 하기 위해서는 14일 (혹은 임의 기간동안의) high와 low그리고 계산된 williams R값을 저장할 새로운 db형태가 필요하다.
db업데이트에 새롭게 필요한 열은 high14day, low14day, williamsr이라는 column을 추가해야된다.

첫번째 방법은 MS-SQL DB의 GUI를 사용해서 하는 방법이다.개체 탐색기에서 dbo.LogDay밑의 열를 우클릭 한 후에, "새 열"을 클릭해서 위의 변수들을 추가 한다.

두번째 방법은 아래의 쿼리를 사용하면 된다.

In [ ]:
ALTER TABLE dbo.LogDay ADD high14day FLOAT NULL, low14day FLOAT NULL, williamsr FLOAT NULL ;

위의 코드는 dbo.LogDay라는 테이블에 위의 변수들 (high14day, low14day, williamsr)을 floating type 그리고 NULL허용으롤 만들어주는 명령어이다. 한번만 수행하면 되기 때문에 따로 코드로 저장할 필요는 없다. 전체 쿼리 코드는 다음과 같다.

In [ ]:
select stockcode, max(logday.pricehigh) AS local_max from [stock].dbo.LogDay group by stockcode;

-- 최근14일간의 최대가격 구하기
select stockcode, logdate, max(logday.pricehigh) over (partition by stockcode order by logdate asc rows 13 preceding) AS local_max from [stock].dbo.LogDay;

-- 최근14일간의 최소가격 구하기

select stockcode, logdate, min(logday.pricelow) over (partition by stockcode order by logdate asc rows 13 preceding) AS local_max from [stock].dbo.LogDay;


-- 최근14일간의 최대가격- 최소가격 구하기
select stockcode, logdate, min(logday.pricelow) over (partition by stockcode order by logdate asc rows 13 preceding) AS local_max from [stock].dbo.LogDay;

/*
update d1
set d1.high14day = (select stockcode, logdate, max(logday.pricehigh) over (partition by stockcode order by logdate asc rows 13 preceding) AS local_max from [stock].dbo.LogDay)
from [stock].dbo.LogDay d1
*/

--테이블에 high14day, low14day, williamsr을 추가하기 위해서 한번만 수행
--ALTER TABLE dbo.LogDay ADD high14day FLOAT NULL, low14day FLOAT NULL, williamsr FLOAT NULL ; 

-- 14일 최대가격 업데이트
update d1
set d1.high14day = d2.local_max 
from [stock].dbo.LogDay d1 join 
(
	select stockcode, logdate, max(logday.pricehigh) over (partition by stockcode order by logdate asc rows 13 preceding) AS local_max
	from [stock].dbo.LogDay
) d2
on d1.stockcode = d2.stockcode and d1.logdate = d2.logdate; 

-- 14일 최소가격 업데이트
update d1
set d1.low14day = d2.local_min 
from [stock].dbo.LogDay d1 join 
(
	select stockcode, logdate, min(logday.pricelow) over (partition by stockcode order by logdate asc rows 13 preceding) AS local_min
	from [stock].dbo.LogDay
) d2
on d1.stockcode = d2.stockcode and d1.logdate = d2.logdate; 

-- 윌리엄스%14 업데이트 
update d1
set d1.williamsr = 100 * ( d1.high14day - d1.priceClose ) / ( d1.high14day - d1.low14day)
from [stock].dbo.LogDay d1
where d1.high14day != d1.low14day

-- 우리은행의 4월18일 기준 전일 williamsr 구하기
select top(1) williamsr from [stock].dbo.LogDay where stockcode = 'A000030' and logdate < 20180418 order by logdate desc;

select logdate, williamsr from [stock].dbo.LogDay where stockcode = 'A000030';

-- 당일의 williamsR 이 80보다 크고, 전일 보다 윌리엄스R 이 작은 종목 : 전일 85 당일 80.. 이런 종목
-- 이런종목을 종가베팅해서 다음날 시가에 판 경우의 sql 우선순위: marketCap
select stockcode, logdate, marketcap, volume, amount, priceClose as buyPrice, (select top(1) priceOpen from [stock].dbo.Logday d3 where d3.stockcode = d1.stockcode and d3.logdate > d1.logdate order by logdate asc ) as sellPrice
from [stock].dbo.LogDay d1 
where williamsr > 80 
	and amount > 5000000000
	and logdate > 20000417 and logdate < 20180504
	and williamsr < ( select top(1) williamsr from [stock].dbo.LogDay d2 where d2.stockcode = d1.stockcode and d2.logdate < d1.logdate order by logdate desc ) order by logdate, marketCap desc;

-- 당일의 williamsR 이 80보다 크고, 전일 보다 윌리엄스R 이 작은 종목 : 전일 85 당일 80.. 이런 종목
-- 이런종목을 종가베팅해서 다음날 시가에 판 경우의 sql 우선순위 : priceClose
select stockcode, logdate, marketcap, volume, amount, priceClose as buyPrice, (select top(1) priceOpen from [stock].dbo.Logday d3 where d3.stockcode = d1.stockcode and d3.logdate > d1.logdate order by logdate asc ) as sellPrice
from [stock].dbo.LogDay d1 
where williamsr > 80 
	and amount > 5000000000
	and logdate > 20000417 and logdate < 20180504
	and williamsr < ( select top(1) williamsr from [stock].dbo.LogDay d2 where d2.stockcode = d1.stockcode and d2.logdate < d1.logdate order by logdate desc ) order by logdate, priceClose asc;



-- 당일의 williamsR 이 80보다 크고, 전일 보다 윌리엄스R 이 작은 종목 : 전일 85 당일 80.. 이런 종목
-- 이런종목의 현재가격,목표가격, 다음날정보까지 출력
select stockcode, logdate, marketcap, volume, amount, priceClose as buyPrice, 
	(priceClose * 1.02 ) as targetPrice,
	(select top(1) logdate from [stock].dbo.Logday d3 where d3.stockcode = d1.stockcode and d3.logdate > d1.logdate order by logdate asc ) as nextDay,
	(select top(1) priceOpen from [stock].dbo.Logday d3 where d3.stockcode = d1.stockcode and d3.logdate > d1.logdate order by logdate asc ) as sellPrice
from [stock].dbo.LogDay d1 
where williamsr > 80 
	and amount > 5000000000
	and logdate > 20180417 and logdate < 20180504
	and williamsr < ( select top(1) williamsr from [stock].dbo.LogDay d2 where d2.stockcode = d1.stockcode and d2.logdate < d1.logdate order by logdate desc ) order by logdate, marketCap desc;


-- 당일의 williamsR 이 80보다 크고, 전일 보다 윌리엄스R 이 작은 종목 : 전일 85 당일 80.. 이런 종목
-- 이런종목의 현재가격,목표가격,10일뒤,타임컷가격,익절한날
select d1.stockcode, d1.logdate, d1.marketcap, d1.volume, d1.amount, priceClose as buyPrice,
	d5.nextDay,
	d5.timecutDate,
	(select priceOpen 
		from [stock].dbo.Logday d3 
		where d3.stockcode = d1.stockcode and d3.logdate > d1.logdate 
		order by logdate asc offset 10 rows fetch next 1 rows only) as timecutPrice,
	d5.targetPrice,
	(select top(1) logdate
		from [stock].dbo.LogDay d3
		where d3.stockcode = d1.stockcode and d3.priceHigh > d5.targetPrice and d3.logdate between nextDay and timecutDate order by d3.logdate asc) as gainSellDate
from [stock].dbo.LogDay d1 join 
(
	select top(100) percent stockcode, logdate, marketcap, volume, amount,
	(priceClose * 1.01 ) as targetPrice,
	(select top(1) logdate 
		from [stock].dbo.Logday d3 
		where d3.stockcode = inner_d.stockcode and d3.logdate > inner_d.logdate 
		order by logdate asc ) as nextDay,
	(select logdate 
		from [stock].dbo.Logday d3 
		where d3.stockcode = inner_d.stockcode and d3.logdate > inner_d.logdate 
		order by logdate asc offset 10 rows fetch next 1 rows only) as timecutDate --10영업일뒤의 날
	from [stock].dbo.LogDay inner_d
	where williamsr > 80 
		and amount > 5000000000
		and logdate > 20170101 and logdate < 20180417
		and williamsr < ( 
			select top(1) williamsr from [stock].dbo.LogDay d2 where d2.stockcode = inner_d.stockcode and d2.logdate < inner_d.logdate order by logdate desc 
		) 
	order by logdate, marketCap desc
) d5 on d1.stockCode = d5.stockCode and d1.logDate = d5.LogDate order by d1.logdate, marketCap desc

github는 다음의 장소를 참조하면 된다.

In [ ]:
# TO BE UPDATED


# Special Thanks to 단테님, Philz님, 룸파님
기본적인 코드 및 환경은 모두 단테님, Philz님, 룸파님 것을 베이스로 했기 때문에 이 문서에서 특별히 한 것은 없다. 이러한 지식과 코드를 공유해주신 두분께 무한한 감사를...

##3.3